# Generated by Django 4.2.4 on 2024-06-23 08:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bannners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.CharField(blank=True, max_length=100, null=True)),
                ('reviews', models.IntegerField(default=1)),
                ('rating', models.IntegerField(default=1)),
                ('image', models.ImageField(upload_to='headers')),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 6, 23, 8, 10, 21, 394543, tzinfo=datetime.timezone.utc))),
            ],
            options={
                'verbose_name_plural': 'Banners',
            },
        ),
        migrations.CreateModel(
            name='BodyMetaTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_tag', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Body Meta Tags',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(upload_to='category_images')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('no_of_store', models.IntegerField(default=0)),
                ('is_popluar', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='MetaTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_tag', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Head Meta Tags',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('image', models.ImageField(upload_to='store_images')),
                ('description', models.TextField()),
                ('rating', models.IntegerField()),
                ('website_url', models.CharField(max_length=255)),
                ('store_of_the_week', models.BooleanField(default=False)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('gmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('categories', models.ManyToManyField(blank=True, to='cms.category')),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(max_length=255)),
                ('expiry_date', models.DateField()),
                ('coupon_url', models.CharField(max_length=255)),
                ('featured', models.BooleanField(default=False)),
                ('is_deal', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(blank=True, default=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.store')),
            ],
        ),
    ]
