# Generated by Django 4.2.4 on 2024-06-23 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannners',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 23, 8, 41, 22, 154234, tzinfo=datetime.timezone.utc)),
        ),
    ]
