# Generated by Django 4.2.4 on 2024-06-24 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_bannners_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannners',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 24, 8, 16, 9, 647685, tzinfo=datetime.timezone.utc)),
        ),
    ]
