# Generated by Django 4.2.4 on 2024-08-04 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_homepageadplacement_alter_bannners_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageadplacement',
            name='banner_placed_on',
            field=models.CharField(blank=True, choices=[('home_page', 'home_page'), ('coupon_page', 'coupon_page')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bannners',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 4, 19, 8, 29, 261119, tzinfo=datetime.timezone.utc)),
        ),
    ]
