# Generated by Django 4.2.4 on 2024-08-18 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_homepageadplacement_banner_placed_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannners',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 18, 8, 30, 28, 817031, tzinfo=datetime.timezone.utc)),
        ),
    ]
