# Generated by Django 4.2.4 on 2024-08-06 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_homepageadplacement_banner_placed_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(upload_to='home-banner')),
                ('banner_name', models.CharField(blank=True, max_length=200, null=True)),
                ('banner_link', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Home Page Banner',
            },
        ),
        migrations.AlterField(
            model_name='bannners',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 6, 12, 25, 34, 33834, tzinfo=datetime.timezone.utc)),
        ),
    ]
