# Generated by Django 4.2.4 on 2024-08-18 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_alter_bannners_created_at'),
        ('cms', '0010_homepagebanner_alter_bannners_created_at'),
    ]

    operations = [
    ]
