# Generated by Django 4.2.4 on 2024-08-18 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_merge_20240818_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannners',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 18, 8, 47, 52, 605160, tzinfo=datetime.timezone.utc)),
        ),
    ]
