# Generated by Django 4.2.4 on 2024-08-19 05:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_merge_20240819_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='usage_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bannners',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 19, 5, 1, 33, 198942, tzinfo=datetime.timezone.utc)),
        ),
    ]
