# Generated by Django 4.2.4 on 2024-08-25 07:46

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_alter_bannners_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannners',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 25, 7, 46, 30, 779323, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='homepagebanner',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
