# Generated by Django 4.2.4 on 2024-08-21 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_alter_bannners_created_at'),
        ('cms', '0013_alter_bannners_created_at'),
    ]

    operations = [
    ]
