# Generated by Django 4.2.4 on 2024-08-25 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_alter_bannners_created_at_and_more'),
        ('cms', '0014_merge_20240821_1004'),
    ]

    operations = [
    ]
