# Generated by Django 4.2.4 on 2024-08-25 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_merge_20240826_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannners',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 25, 19, 36, 22, 683809, tzinfo=datetime.timezone.utc)),
        ),
    ]
