# Generated by Django 4.2.4 on 2024-12-23 08:32

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_alter_bannners_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorePageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(upload_to='store-banner')),
                ('banner_name', models.CharField(blank=True, max_length=200, null=True)),
                ('banner_link', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Store Page Banner',
            },
        ),
        migrations.AlterField(
            model_name='bannners',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 23, 8, 32, 4, 450579, tzinfo=datetime.timezone.utc)),
        ),
    ]
