# Generated by Django 4.2.4 on 2024-12-27 10:35

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_storepagebanner_alter_bannners_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessUrls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('store', 'store'), ('category', 'category'), ('coupon', 'coupon')], max_length=200)),
                ('base_url', models.URLField(default='https://empireofblogs.net')),
                ('middle_url', models.CharField(choices=[('stores', 'stores'), ('categories', 'categories'), ('coupons', 'coupons')], max_length=100)),
                ('unique_key', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('full_url', models.URLField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bannners',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 27, 10, 35, 4, 51372, tzinfo=datetime.timezone.utc)),
        ),
    ]
