# Generated by Django 4.2.4 on 2025-01-04 07:46

import datetime
from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_alter_bannners_created_at_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='short_text',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bannners',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 4, 7, 46, 50, 965072, tzinfo=datetime.timezone.utc)),
        ),
    ]
