# Generated by Django 4.2.4 on 2024-07-01 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_contact_alter_blogcategory_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='is_latest_blog',
            new_name='is_featured_blog',
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 15, 23, 49, 630542)),
        ),
    ]
