# Generated by Django 4.2.4 on 2024-07-01 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_is_latest_blog_blog_is_featured_blog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 15, 27, 9, 429086)),
        ),
    ]
