# Generated by Django 4.2.4 on 2024-08-25 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_newsletter_alter_blog_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 25, 12, 46, 30, 782144)),
        ),
    ]
